config/routes.rb
Fitafy::Application.routes.draw do

  resources :user_records, only: [:create]
  resources :invites,      only: [:index]

  resources :contact_importer_records, only: [:index]

  #---------- SIMPLE ----------#

  get "unsubscribe/:perishable_token", to: "unsubscribes#update", as: :unsubscribe

  #---------- STATIC ----------#

  get "pages/home"
  root to: "pages#home"

  get   "pages/terms_of_service"
  get   "pages/privacy"
  match "terms_of_service", to: "pages#terms_of_service"
  match "privacy",          to: "pages#privacy"
end

app/models/invite/manager.rb
module Invite
  class Manager
  	attr_reader :sender, :receivers, :message, :records

    def initialize(params)
      create_and_add_sender(params.fetch('sender'))
      @message = params.fetch('message')
      create_and_add_receivers(params.fetch('receivers'))
      create_and_add_records
    end

    def send_messages
      records.each { |record| invite_mailer_sender(record.id) }
    end

    def count
      records.length
    end

    private

    def create_and_add_sender(email)
      @sender = UserRecord.find_or_create_by_email(email)
      User::Manager.new(sender).save_invite_sending_user
    end

    def create_and_add_receivers(receiver_details)
      @receivers = []
      receiver_details.each { |receiver| create_and_add_receiver receiver }
    end

    def create_and_add_receiver(receiver)
      record = user_record(receiver.fetch('contact'))
      create_receiver record    	
    end

    def create_receiver(record)
      receivers << User::Manager.new(record).save_invited_user
    end

    def create_and_add_records
      @records = []
      receivers.each { |receiver| create_invite_record(receiver) }
    end

    def create_invite_record(receiver)
      records << InviteRecord.create(sender_id: sender.id, receiver_id: receiver.id, message: message)
    end

    def user_record(contact)
      UserRecord.find_or_create_by_email(contact)
    end

    def invite_mailer_sender(record_id)
      Resque.enqueue(InviteMailerSender, record_id)
    end
  end
end

app/models/invite_record.rb
class InviteRecord < ActiveRecord::Base
  attr_accessible :sender_id, :receiver_id, :message

  belongs_to :sender,   class_name: 'UserRecord'
  belongs_to :receiver, class_name: 'UserRecord'
end

app/models/user/manager.rb
module User
  class Manager

    attr_reader :record

  	def initialize(record)
      ensure_correct_class record
  	  @record = record
  	end

    def add_to_database
      update_perishable_token!
      record.save ? send_welcome_email : false
    end

    def unsubscribe
      record.subscribed = false
      update_perishable_token! if record.save
      record
    end

    alias_method :save_invited_user, :unsubscribe

    def save_invite_sending_user
      record.id ? true : add_to_database
    end

    def subscribed?
      record.subscribed == true
    end

    # --------------------------------------------------
    # Delegated methods: this is due to zeus not being able
    # to handle method delegation
    # --------------------------------------------------

    def perishable_token
      record.perishable_token
    end

    def email
      record.email
    end

    private

    def ensure_correct_class(record)
      unless record.class == UserRecord
        raise WrongClassError, "The record is a #{record.class} and should be a UserRecord"
      end
    end

    def update_perishable_token!
      record.perishable_token = dynamic_md5_digest
    end

    def send_welcome_email
      Resque.enqueue(SignupMailerSender, record.email)
    end

    def dynamic_md5_digest
      Digest::MD5.hexdigest("#{Time.now}-#{record.email}")
    end
  end
end

app/models/user_record.rb
class UserRecord < ActiveRecord::Base
  attr_accessible :email

  validates :email, presence: true, uniqueness: true, email: true

  has_many :invite_records, foreign_key: 'sender_id',   dependent: :destroy
  has_many :invite_records, foreign_key: 'receiver_id', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_importer_records_controller.rb
class ContactImporterRecordsController < ApplicationController
  respond_to :json

  def index
  	@records = CopyGenerator::ContactImporterRecordsCopy.all
  	render json: @records
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  # respond_to :json, only: :create

  def index
  	@title = 'Invite Your Friends To Fitafy'
    @user_email = params[:user_email] if params[:user_email]
  end

  def create
  	invite = Invite::Manager.new(params)
    invite.send_messages
    respond_to { |format| format.json { return true } }
  end

  private

  def invite_sent_copy(count)
  	CopyGenerator::InviteCopy.invites_sent(count)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  	@user = UserRecord.new
  	@copy = CopyGenerator::HomepageCopy
  	# @usp         = CopyGenerator::HomepageCopy.usp
  	# @sub_heading = CopyGenerator::HomepageCopy.sub_heading
   #  @features    = CopyGenerator::HomepageCopy.features
  end
end

app/controllers/unsubscribes_controller.rb
class UnsubscribesController < ApplicationController
  def update
  	@record = UserRecord.find_by_perishable_token(params[:perishable_token])
  	@user   = User::Manager.new(@record)

  	if @user.unsubscribe
  	  flash[:success] = CopyGenerator::EmailCopy.unsubscribe
  	  redirect_to root_path
  	end
  end
end

app/controllers/user_records_controller.rb
class UserRecordsController < ApplicationController

  def create
  	@record = UserRecord.new(params[:user_record])
    @user   = User::Manager.new(@record)
  	@user.add_to_database ? redirect_to_invites : rerender_homepage
  end

  private

  def redirect_to_invites
    flash[:success] = CopyGenerator::UserCopy.first_sign_up
    redirect_to controller: 'invites', action: 'index', user_email: @user.email
  end

  def rerender_homepage
    @title        = ''
    @user         = UserRecord.new
    @copy         = CopyGenerator::HomepageCopy
    @error        = "'#{@record.email.upcase}' #{@record.errors.messages[:email][0]}!"
    flash[:error] = CopyGenerator::UserCopy.error_first_sign_up
    render 'pages/home'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def section_title
    if @title
      @title.upcase
    else 
      'Fitafy'
    end
  end

  def favicon_url
    "https://d3jpl91pxevbkh.cloudfront.net/hdxvaer2w/image/upload/v1362900687/kossw7tuu2yogyptdshg.png"
  end

  def star2_icon_url
    "https://d3jpl91pxevbkh.cloudfront.net/hdxvaer2w/image/upload/v1362901507/bsimss6lfenjyhy6m5t1.png"
  end

  def regular_hard_red_icon_image_url
    "https://d3jpl91pxevbkh.cloudfront.net/hdxvaer2w/image/upload/v1362902460/iujp25dwiepx8bdxra3z.png"
  end

  def regular_hard_grey_icon_image_url
    "https://d3jpl91pxevbkh.cloudfront.net/hdxvaer2w/image/upload/v1362902876/z8prqooqvr6ry6w8d0w6.png"
  end

  def ajax_loader_gif_url
    "https://d3jpl91pxevbkh.cloudfront.net/hdxvaer2w/image/upload/v1362903578/synfhl7zq00z3cq1dnnk.gif"
  end
end

app/views/application/_chromeframe.html.haml
-# Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
-# chromium.org/developers/how-tos/chrome-frame-getting-started
/[if lt IE 7 ]
  %p.chromeframe
    Your browser is <em>ancient!</em>
    <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.

app/views/application/_footer.html.haml
%footer
  %aside
    %strong.logo
      = link_to 'fitafy', root_path
    %nav.footer-nav
      %ul
        %li fitafy, Copyright &copy; #{ Date.today.year }
        %li= link_to "Terms & Conditions", terms_of_service_url
        %li= link_to "Privacy Policy", privacy_url

app/views/application/_head.html.haml
%head
  %meta{ :charset => "utf-8" }/

  -# Use the .htaccess and remove these lines to avoid edge case issues.
  -# More info: h5bp.com/b/378
  %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }/
  %meta{ name: "description", content: "Personal Trainer client leads service" }/
  %meta{ name: "author", content: "Vlad Ivanovic" }/

  %title= section_title

  %meta{ :name => "description", :content => "" }/

  -# Mobile viewport optimized: h5bp.com/viewport
  %meta{ :name => "viewport", :content => "width=device-width" }/

  %link{ :type => "image/x-icon", :href => favicon_url, :rel => "icon" }/

  %link{ :href => favicon_url, :rel => "shortcut icon" }/

  = stylesheet_link_tag "application"

  -# More ideas for your <head> here: h5bp.com/d/head-Tips

  = csrf_meta_tag

app/views/application/_header.html.haml
%header
  %h1= section_title unless params[:action] == 'home'

app/views/invites/_invite_from.html.haml
#invite_from
  %header
    %b
      Invite From

  - if @user_email
    %p.user_email= @user_email

  - else
    .user{ "ng-hide" => "editSenderEmailMode" }
      %span.edit
        %i.icon-pencil#edit-my-email{ "ng-click" => "editSenderEmail()" }
      %p.user_email {{inviteFrom}}

    .no_user{ "ng-show" => "editSenderEmailMode" }
      %p Before you can add friends you need to let us know who you are, if you haven't registered for updates from fitafy we'll add you now.

      %form.users_email{ "name" => "senderForm", "ng-submit" => "addSenderEmail(sender)" }
        %input#user_email{ "type" => "email", "placeholder" => "your@email.com", "ng-model" => "sender.email", "required" => true }
        %button.add{ "ng-disabled" => "senderForm.$invalid" } ADD YOUR EMAIL

app/views/invites/_invite_message.html.haml
%div#invite_message
  %span.edit
    %i.icon-pencil#edit_message{ "ng-click" => "editMessageMode()" }
  %p{ "ng-hide" => "editMessage" } {{message}}

  %form{ "ng-show" => "editMessage", "ng-submit" => "changeMessage(message)" }
    %textarea#message_form{ "ng-model" => 'message' }
    %button.btn-success SAVE

app/views/invites/_invite_to.html.haml
%header
  %b
    Invite To
    %span.badge.badge-info.friend-count {{friends.length}}

.invited-friends-list
  %form.css-form.add-friend{ "ng-submit" => "addFriend(friend)", 'name'=> 'form', "novalidate" => true }
    %input#friends_name{ 'type'=> 'text', 'placeholder'=> "Friend's Name", "ng-model" => "friend.name", "required" => true }
    %input#friends_email{ 'type'=> 'email', 'placeholder'=> "friends@email.com", "ng-model" => "friend.contact", "required" => true }
    %button.btn-success.add{ "ng-disabled" => "form.$invalid" } ADD FRIEND

  %ul
    %li.invited-friend{ "ng-repeat" => "friend in friends"}
      %img.profile-pic{ 'src'=> "http://static.bleacherreport.net/images/redesign/avatars/default-user-icon-profile.png"}
      %b.name {{friend.name}}
      %br
      %small.muted {{friend.contact}}
      %span.delete
        [
        %a{ 'href'=> '', "ng-click" => "removeFriend($index)" } X
        ]

app/views/invites/index.html.haml
#invites
  %aside.row-fluid
    .span12

      %p We want as many fitness professional as possible to benefit from getting leads from fitafy.

      %p If you have friends or colleagues you think would be interested why not spread the word?

  %section.row-fluid

    %section.span5{ "ng-controller" => "InviteFriendsCtrl" }
      %header
        %b Your Invite

      = render 'invite_message'

      %aside
        = render 'invite_to'

        = render 'invite_from'

        %button{ "ng-click" => "sendInvite()", "ng-class" => "buttonClass" } {{ctaMessage}}

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    .message{ :class => "alert alert-#{key}" }
      %a.close{"data-dismiss" => "alert"} x
      = value

app/views/layouts/_navigation.html.haml
/ = navigation_renderer.render.html_safe

app/views/layouts/application.html.haml
!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
- html_tag :class => "no-js", :lang => "en", "ng-app" => "Fitafy" do
  = render "head"

  %body{ :class => "#{ controller.controller_name } container-fluid" }
    %noscript You need to enable Javascript to get the most out of fitafy

    %a{ :accesskey => 's', :href => '#main', class: 'hidden' } skip to content
    = render "chromeframe"

    %nav= render "layouts/navigation"

    %section#main{ :role => "main" }
      = render "layouts/flashes"

      = render "header"

      = yield

    = render "footer"

    = javascript_include_tag "application"

= debug(params) if Rails.env.development?

app/views/layouts/invites.html.haml
!!! 5
%html
  %head
    %title FITAFY - INVITES
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = yield :javascript
    = csrf_meta_tag

  %body
    #section#main
      #container= yield

app/views/pages/home.html.haml
%section#usp

  .usp_sign_up

    %header
      %h1= @copy.usp

    %p= @copy.sub_heading

    .email_form
      = simple_form_for @user, validate: true do |f|
        = f.error_notification
        = f.input :email, label: false, placeholder: 'your@email.com', input_html: { class: 'fitaform cta' }
        = f.submit 'SIGN UP', class: 'btn cta'

      .sign_up_error= @error if @error

%aside.box_list.homepage
  %ul
    - @copy.features.each do |f|
      %li.homepage_features
        %header
          %h3= f.title
        %img{ src: "#{f.image}" }
        %p= f.copy

app/views/pages/privacy.html.haml
%h5#information_collection What information do we collect?
%p We collect from you when your register on our website or app and if you fill out a form. As you register on our site you will be asked to enter your email address. It is also possible to use the software trial anonymously.

%h5#why Why do we collect your information?

%p We may use any information we collect for the following ways:
%ul
  %li To assist us create a better experience for you when using our website and service.
  %li Your information helps respond to your customer support and service needs.
  %li Your information and feedback helps us improve our website and services.
  %li Tailoring a website, application, or FITAFY marketing to your likely interests.
  %li Conducting market research about our customers, their interests, and the effectiveness of our marketing campaigns.
  %li Reducing fraud, software piracy, and protecting our customers.
  %li Sending you information about FITAFY, new application releases, special offers, and similar information.
  %li The FITAFY website and services may include buttons, tools, or content that link to other companies’ services. We may collect information about your use of these features.

%h5#accessing_updating_your_info Accessing and updating your personal information

%p Whenever you use our services, we aim to provide you with access to your personal information. If that information is wrong, we strive to give you ways to update it quickly or to delete it – unless we have to keep that information for legitimate business or legal purposes. When updating your personal information, we may ask you to verify your identity before we can act on your request.

%p We may reject requests that are unreasonably repetitive, require disproportionate technical effort (for example, developing a new system or fundamentally changing an existing practice), risk the privacy of others, or would be extremely impractical (for instance, requests concerning information residing on backup tapes). 

%p Where we can provide information access and correction, we will do so for free, except where it would require a disproportionate effort. We aim to maintain our services in a manner that protects information from accidental or malicious destruction. Because of this, after you delete information from our services, we may not immediately delete residual copies from our active servers and may not remove information from our backup systems. 

%h5#third_parties Do we disclose any of your information to 3rd parties?
%p We do not disclose, rent or sell and of your sensitive personal information to any third parties. This does not include trade partners that FITAFY to operate the business, conduct the business and service you. These partners also agree to this privacy policy and treat of your personal information. The FITAFY website and services may include buttons, tools, or content that link to other companies’ services. We may collect information about your use of these features. 

%p We shall however disclose information should it be deemed appropriate for law enforcement, to enforce our site or service policies or to protect our rights or property. 

%p FITAFY may also share your information
%ul
  %li When you agreed to the sharing.
  %li Within the FITAFY family of companies for purposes described in this privacy policy.
  %li When we are required to provide information in response to a subpoena, court order, or other applicable law or legal process.
  %li When we have a good faith belief that the disclosure is necessary to prevent or respond to fraud, defend our websites or applications against attacks, or protect the property and safety of FITAFY, our customers and users, or the public.

%p If we merge with or are acquired by another company; we sell an FITAFY website, application, or business unit or all or a substantial portion of our assets are acquired by another company. In those cases your information will likely be one of the assets that is transferred.

%h5#external_links External links to the FITAFY website

%p We have links on our website to 3rd party products or services which have their own independent privacy policies. We hold no responsibility or liability for the content and activities of these sites. Please use or view the sites at your own discretion. 

%p The FITAFY website and services may include buttons, tools, or content that link to other companies’ services. We may collect information about your use of these features. 

%h5#notification_of_changes Notification of Changes 

%p Any changes to this Privacy Policy will be posted to this Website and emailed to the last email address you have given to us, and will become effective as of the later of the date we post on the Website or, send the email. 

%p You may object to any changes within 20 days after they are posted on our Website or delivered to you, in which case none of the proposed changes will be effective with respect to information that we have already collected from you; but will apply only to information we collect or access from you in the future.

%p There are purposes, other than marketing, for which we are not willing or able to treat information of any open account differently from that of any other open account. Therefore, if you object to changes in our Privacy Policy which relate to those purposes, we will have to terminate your account. In contrast, in the event we ever changed our Privacy Policy to allow us to have an expanded right to use or disclose Personal Information for marketing purposes, you would be able to opt out without any such termination.

%h5#change_log Change Log
%ul
  %li October 2012, initial document live

app/views/pages/terms_of_service.html.haml
= render 'terms_of_service_copy'

app/views/workouts/_show_exercise.html.haml
%li.workout_exercise.big_box_list.row.well{ "data-id" => exercise.order_number }

  .w_e_order.span1
    - if can? :manage, @workout
      = render partial: "exercises/order_form", locals: { exercise: exercise, value: -1, direction: "up" }
      %h2.order_numbers= exercise.safe_order
      = render partial: "exercises/order_form", locals: { exercise: exercise, value: 1, direction: "down"  }

    - else
      %h2= exercise.safe_order

  .w_e_details.span3
    %h3= link_to exercise.name.titleize, exercise_path(exercise.exercise)
    %br

    .workout_form_group.instructions
      .workout_value.instructions{"data-value" => exercise.id}
        %h5 Instructions
        %p= exercise.safe_instructions.humanize
        = link_to_show_form @workout, "instructions", exercise.id
      .hidden.workout_form.instructions{"data-value" => exercise.id}
        - if can? :manage, @workout
          = simple_form_for exercise, remote: true do |f|
            = f.input :instructions, input_html: { rows: 6 }
            = f.submit "UPDATE WORKOUT", class: "btn btn-primary btn-mini"
        = link_to_hide_form @workout, "instructions", exercise.id
    %br
    %br

    %table.workout_exercise_details
      %thead
        %tr
          %th
            %h5 Sets
          %th
            %h5 Muscle
          %th
            %h5 Equipment

      %tbody
        %tr
          %td
            .workout_form_group.sets
              .workout_value.sets{"data-value" => exercise.id}
                = exercise.safe_sets
                = link_to_show_form @workout, "sets", exercise.id
              - if can? :manage, @workout
                .hidden.workout_form.sets{"data-value" => exercise.id}
                  = simple_form_for exercise, remote: true do |f|
                    = f.input :sets, input_html: { class: "thin_form_element" }
                    = f.submit "UPDATE", class: "btn btn-primary btn-mini"
                  = link_to_hide_form @workout, "sets", exercise.id
          %td= exercise.muscle.titleize
          %td= exercise.equipment_name.titleize

    %br
    - if can? :delete, @workout
      %th= link_to "REMOVE", workout_exercise_path(exercise), confirm: @snapz_confirm, method: :delete, class: "btn btn-danger btn-mini"

app/views/workouts/_workout_aside.html.haml
%aside
  = link_to_favorite_workout @current_user, @workout

  = link_to_edit_or_copy_workout @current_user, @workout

  = link_to_download_workout_pdf @workout

app/views/workouts/_workout_exercises_form.html.haml
%p#tab_sort_by
  SORT BY:
  - @exercise_types.each do |type|
    = link_to type.upcase, sort: type
    |

%table.table.table-bordered.table-striped

  %tbody#workout_exercises
    - @exercises.each do |exercise|
      = f.fields_for :workout_exercises, @workout.new_workout_exercise do |e|
        %tr#workout_exercises_fields
          = e.hidden_field :exercise_id, value: exercise.id
          %td#workout_exercises_sets
            %h4= exercise.name.titleize
            %br= e.input :sets, collection: 1..10, label: "Add Sets:"
          %td#workout_exercise_notes= e.input :notes, input_html: { rows: 4 }

app/views/workouts/show.html.haml
.workout_form_group
  .workout_value.name
    = link_to_show_form @workout, "name"

  .hidden.workout_form.name
    = link_to_baby_form current_user, @workout, :name, [current_user, @workout]
    = link_to_hide_form @workout, "name"
%br

.workout_form_group.notes
  .workout_value.notes
    %h5 NOTES
    %p= @workout.safe_notes.capitalize
    = link_to_show_form @workout, "notes"
  .hidden.workout_form.notes
    - if can? :manage, @workout
      = simple_form_for [current_user, @workout], remote: true do |f|
        = f.input :notes, input_html: { rows: 6 }
        = f.submit "UPDATE WORKOUT", class: "btn btn-primary btn-mini"
      = link_to_hide_form @workout, "notes"

%br

%section.row
  %article.span6
    %header
      %h5 EXERCISES
    %ul.workout_exercises
      = @workout.render_exercises self
    = link_to_add_exercise @workout
  %br

  %aside.span3.well
    = render "stats"
    = render "cta_buttons"

= render partial: "add_exercise_modal"